### ISSUE TITLE
Graphik-Theme wg. Rot-Grün-Schwäche

### ISSUE THREAD

**Issue by Bia-Ka** [FOM-ifes/VL-Fallstudien#1]
Hallo zusammen,

gestern habe ich die Fallstudie zur Lego-Modellierung beendet und im letzten Teil haben wir die drei Lego-Serien in den Abbildungen ja eingefärbt. Ein Student meldete sich, das er das aufgrund seiner Rot-Grün-Schwäche leider nicht erkennen könnte. Das Thema hatten wir für unsere Unterlagen ja schon einmal:

Spricht etwas dagegen, auch in den Fallstudien eine entsprechend barrierefreie Variante in den Graphiken zu wählen? Wenn nicht, würdest du, @TabeaG , das einmal umsetzen? (Sind sicherlich nicht viele Graphiken, in denen das relevant ist).

VG Bianca

**Comment by NMarkgraf** [comment]
Ja, es spricht etwas dagegen! Ich kann diese Farben nicht benennen! Daher ist es für mich als Dozierender schwerer die korrekten Grafen zu beschreiben. Statt neuer Farben wäre ich dafür hier auf gepunktet und gestrichelt zu wechseln!

**Comment by NMarkgraf** [comment]
Status hier?
