### ISSUE TITLE
Feedback zur HKA-Fallstudie

### ISSUE THREAD

**Issue by CelineWidera** [FOM-ifes/VL-Fallstudien#3]
Hallo zusammen,

ich habe meinen Vorschlag zur Fallstudie der Hauptkomponentenanalyse hochgeladen und würde gerne eure Meinung dazu hören. Ich habe auch im Dokument selbst Kommentare bzw. Fragen verfasst, auf die ihr gerne reagieren könnt (bspw. wie sinnvoll ein Biplot bei diesen Ergebnissen ist).

Und bitte wundert euch nicht, inhaltlich müsste die Fallstudie noch eingebettet werden, dafür kenne ich mich aber zu schlecht mit dem IRLL Projekt aus.

Danke schonmal :)
Celine

**Comment by Bia-Ka** [comment]
Liebe @CelineWidera,
schon einmal vielen Dank für deinen Aufschlag!! Ich würde sagen: Feuer frei ans Team!!
LG Bianca
P.S.: Bin mir in Bezug auf den Biplot auch unsicher - ich muss gestehen, ich erkenne wenig. 😎 
Gibt es die Möglichkeit da hineinzuzoomen?

**Comment by statistical-thinking** [comment]
Auch von mir vielen Dank für den Aufschlag :-) Bei mir in der Lehre haben die Master-Studierenden in der Regel kein Vorwissen bzgl. der Unterscheidung in Faktoren oder Hauptkomponenten, bzw. haben sie dieses Wissen aus dem Bachelor wieder verdrängt. Eventuell könnte man das noch beispielhaft in der Einleitung ergänzen. Und das Konzept der Eigenwerte / Eigenvektoren ist auch so ein Thema -> hier sollten wir vielleicht noch eine Hilfestellung oder Erläuterung einpflegen, was meint Ihr? Ich selbst nehme immer das Mona Lisa Beispiel (Wiki) mit zwei Vektoren, um zumindest rudimentär die Idee zu verdeutlichen... Viele Grüße und merci, Dennis

**Comment by CelineWidera** [comment]
Vielen Dank für eure Rückmeldungen!

Zu Dennis:
Ich werde das Konzept der Eigenwerte/-vektoren ergänzen.

Zu Matthias:
- Die Zeilen zu den Paketen passe ich an.
- Dein Buch muss ich mir wohl mal anschauen und die Tests, ob Daten für eine HKA geeignet sind, werden ergänzt. 
- Das Konzept der Rotation habe ich im Zuge der Faktorenanalyse kennengelernt aber dazu gibt es keine eigene Fallstudie, richitg?
- Zum Varianzkriterium: Ich habe für dieses Kriterium einen Wert von 0.8 gelernt. Soll ich das so übernehmen? (In der Fallstudie liegen die Varianzen aller HKs darunter.)

**Comment by Bia-Ka** [comment]
Hallo zusammen,

richtig, zur Faktorenanalyse haben wir keine eigene Fallstudie vorgesehen, daher ist die Integration des Rotationskonzeptes hier eine gute Idee! Vielleicht sogar inkl. der Abbildungen, die wir im alten Skript dazu hatten und auch bei Matthias im Buch zu finden sind?
Ich würde in Bezug auf die erklärte Varianz gar nicht unbedingt auf einen Grenzwert verweisen, sondern eher auf der Ebene bleiben, dass durch die HK immer ein möglichst großer Teil der ursprünglichen Variation erklärt werden sollte.

**Comment by NMarkgraf** [comment]
Kann zu?
