### ISSUE TITLE
In quarto nutzen wir today statt R Code! ;-)

### ISSUE THREAD

**Issue by NMarkgraf** [FOM-ifes/VL-Fallstudien#5]
Wie gerade wieder bei Karsten (@luebby) gesehen habe, nutzen manche im YAML Kopf noch wie vor gefühlt 100 Jahren R Code um das aktuelle Datum zu setzten. 
Das ist aber nicht mehr nötig!

Ein einfaches
'date: today' tut es auch. Der Vorteil ist, dass es wunderbar mit dem 'lang: de' harmoniert. ;-)

**Comment by luebby** [comment]
@NMarkgraf : Du kennst mich doch. Alt und strukurkonservativ. Und Teil der Mehrheitsgesellschaft von [Regel 3](https://teachtogether.tech/en/index.html).

Aber **Danke**. Wusste ich nicht.

**Comment by NMarkgraf** [comment]
@luebby : Ja, ich weiß. Ich wünschte ich könnte sagen, wenn Du gestern meinen Kurs besucht hättest, dann wüsstest Du das. --- Kann ich aber leider nicht. ;-) -- Greg hat mit allen 10 Punkten recht.

Aber noch etwas, als alter TeXniker und Meckerhannes:

- $Pr( X \mid Y)$ liesst sich vielleicht nicht so gut, aber sieht besser aus also $Pr(X | Y)$. ;-)

- Niemand kennt den Satz von Bayes, er ist alles andere als "weltberühmt" B-)

- Sätze mit zwei Doppelpunkten sind ekelhaft: und meisten: nicht sinnvoll!

- Statt ` ```{r resampling}` schreibt man in quarto besser:

```
```{r}
#| label: resampling
```

- Auch wenn es geht, wir haben die Leuten statt `ki95 <- qdata( ~ prop_richtig, data = Bootvtlg, p = c(0.025, 0.975))` beigebracht, das die Daten immer zu letzt stehen, also `ki95 <- qdata( ~ prop_richtig, p = c(0.025, 0.975), data = Bootvtlg)`!

- Auch bin ich der Meinung das "\pi|(Y=y)" eigentlich "\pi|_{(Y=y)}" lauten müsse, oder?

- Und dann ganz unten. Gibt mensch den Tipp nicht eigentlich immer NACH den Fragen?

Aber sonst alles (auf dem ersten Blick jedenfalls) super! -- Ich wollte einfach nur mal etwas meckern. :-P

**Comment by NMarkgraf** [comment]
Kann zu?
