### ISSUE TITLE
Fallstudie 5c Bayes: Prior App?

### ISSUE THREAD

**Issue by luebby** [FOM-ifes/VL-Fallstudien#6]
Für die Bayes Fallstudie [5c_Früherkennung](https://github.com/FOM-ifes/VL-Fallstudien/blob/master/5_inferenzstatistik/5c_Fr%C3%BCherkennung.qmd) habe ich die *bewährte* <https://fomshinyapps.shinyapps.io/BaBeBi/> App verwendet. Theorie, Praxis und Empirie sagt, dass so die *Prior Elicitation* eher schwer fällt, am einfachsten noch vielleicht über die *Roulette* Methode *Chips and Bins*, siehe <https://fomshinyapps.shinyapps.io/Chips-and-Bins/>. Was meint Ihr?

**Comment by NMarkgraf** [comment]
Es mag ja sein, dass ich doof bin, aber ganz ehrlich? Ich verstehe so aus dem Zusammenhang gerichtet KEINE der beiden shinyapps und würde sie vermutlich daher überhaupt nicht einsetzten. Sie sind zu kurz gedacht, zu wenig erklärenden Begleittext und daher -- so denke ich -- nicht wirklich hilfreich.

**Comment by luebby** [comment]
Ich sage nur Tonspur ;-)
Die Lehrende sollte das natürlich live zeigen und erklären was wie warum. Ist so nicht für das Selbststudium gedacht!

**Comment by NMarkgraf** [comment]
Tonspuren sterben mit dem Sprecher, Texte bleiben für die Ewigkeit. -- Wer glaubt die Tonspur macht die Musik, der muss leider sehen, dass nur die Noten für die Ewigkeit bleiben und nicht der Klang!
Und die Ausrede für das "ich bin zu faul das sauber zu schreiben" zu nutzen, aka "Die Lehrende sollte das natürlich live zeigen und erklären was wie warum. Ist so nicht für das Selbststudium gedacht!" ist auch -- wie wir wissen -- kurzsichtig. Denn genutzt wird der Kram nur, wenn die Lehrenden es auch selber verstehen! 

Und ja, @luebby , wir sehen das hier anders. Dass weiß ich. Aber, genau wie Du, glaube ich, dass ich recht habe! B-)

**Comment by NMarkgraf** [comment]
Kann zu?
