### ISSUE TITLE
Random Forest

### ISSUE THREAD

**Issue by TanjaKistler** [FOM-ifes/VL-Fallstudien#7]
Habe die Fallstudie zu RF eingefügt - an Stelle - 9 - . Ggf. muss man das aus der Logik umnummerieren?
Lösung steht auch drin.
Gern durchschauen, Kritik und Optimierungen sind willkommen.
Habe absichtlich die Referenzen drin gelassen (Wissenschaft und Transparenz usw ;) ) kann die noch direkt verlinken - wie Celine es auch gemacht hat.

**Comment by NMarkgraf** [comment]
Ich schau gerade mal etwas drüber und korrigiere so kleinere Typos.

Aber: 
- "Goldstandartmethode"? 
- Körperfettanteil misst doch heute fast jede neue Waage, wieso sollte das teuer sein?
- `cat(...)` Anweisungen sind nicht wirklich sinnvoll, oder?
- Ich bin mir auch nicht sicher was mse und rsq in der Ausgabe vom RF angeht. Was genau sind diese Werte, bzw. was sind sie NICHT.

Viele Grüße 
Norman

**Comment by TanjaKistler** [comment]
> Ich schau gerade mal etwas drüber und korrigiere so kleinere Typos.
> 
> Aber:
> 
>     * "Goldstandartmethode"?
> 
>     * Körperfettanteil misst doch heute fast jede neue Waage, wieso sollte das teuer sein?
> 
>     * `cat(...)` Anweisungen sind nicht wirklich sinnvoll, oder?
> 
>     * Ich bin mir auch nicht sicher was mse und rsq in der Ausgabe vom RF angeht. Was genau sind diese Werte, bzw. was sind sie NICHT.
> 
> 
> Viele Grüße Norman

Guten Morgen,
Danke dir!
Der Körperfettanteil der Waagen ist sehr ungenau. Wenn man es korrekt bestimmen mag, dann ist es teuer. 
Stimmt cat Angaben wollte ich noch entfernen, danke!
Zum letzten Punkt - daher nochmla die Berechnung...ausreichend?

**Comment by NMarkgraf** [comment]
Hallo @TanjaKistler ,

ich glaube nur nicht, dass wir den "Goldstandard" ernennen sollten, wenn dann schon eher, wieso die Methode, die offenbar jeden Unwissenden sofort einfällt, Waage nicht wirklich gut ist. Wir müssen den Leuten erklären, wieso wir es anders und damit ggf. besser machen wollen. Sonst sieht das alles mehr nach Fingerübung und akademisches Unfug aus. -- Danke ich. -- Anders können wir, so glaube ich, eher Interesse wecken.

Nun ich denke schon, dass wir, liebe @TanjaKistler , hier erklären sollten WAS das für Werte sind und AUF WELCHER Grundlage die angegeben werden. -- Weißt Du das aus dem Stand? ;-)
Ich habe einiges nachdenken müssen um darauf zu kommen, wenn ich ehrlich bin. 

Wenn Du die die Variable $mse und $rsq anschaust, bekommst Du nämlich 500 Werte. Welche und wieso genau der, wird nun bei der Ausgabe dort angezeigt. -- Ich denke, dass wäre wichtig, oder?

**Comment by TanjaKistler** [comment]
> Hallo @TanjaKistler ,
> 
> ich glaube nur nicht, dass wir den "Goldstandard" ernennen sollten, wenn dann schon eher, wieso die Methode, die offenbar jeden Unwissenden sofort einfällt, Waage nicht wirklich gut ist. Wir müssen den Leuten erklären, wieso wir es anders und damit ggf. besser machen wollen. Sonst sieht das alles mehr nach Fingerübung und akademisches Unfug aus. -- Danke ich. -- Anders können wir, so glaube ich, eher Interesse wecken.
> 
> Nun ich denke schon, dass wir, liebe @TanjaKistler , hier erklären sollten WAS das für Werte sind und AUF WELCHER Grundlage die angegeben werden. -- Weißt Du das aus dem Stand? ;-) Ich habe einiges nachdenken müssen um darauf zu kommen, wenn ich ehrlich bin.
> 
> Wenn Du die die Variable $mse und $rsq anschaust, bekommst Du nämlich 500 Werte. Welche und wieso genau der, wird nun bei der Ausgabe dort angezeigt. -- Ich denke, dass wäre wichtig, oder?

Celine und ich haben nun einiges noch hinzugefügt und erklärt. Ein ganz liebes Dankeschön an dich, liebe Celine!
Ich denke und hoffe es ist nun transparenter. 
Goldstandard ist nicht von mir so benannt, sondern gilt in der Literatur als solcher - übrigens ein üblicher Begriff in dem Bereich ;) 
Dass eine zu-Hause-Waage eine eher ungenaue und schlechte Operationalisierung/Schätzung von in vivo Daten ist, habe ich nun nicht extra erklärt, geht aber ja vielleicht ein wenig besser hervor. Sonst schreibe ich gerne ein AddOn.

**Comment by Bia-Ka** [comment]
Das kann jetzt zu, oder?

**Comment by NMarkgraf** [comment]
Ja!
