### ISSUE TITLE
Warnung in  Fallstudie Gemeinden zu datatable

### ISSUE THREAD

**Issue by Bia-Ka** [FOM-ifes/VL-Fallstudien#8]
Ich erhalte beim Rendern aktuell diese Warnmeldung:
`Warning in instance$preRenderHook(instance): It seems your data is too big for
client-side DataTables. You may consider server-side processing:
https://rstudio.github.io/DT/server.html`

Ist das bei euch auch so und kann man etwas dagegen tun?

**Comment by NMarkgraf** [comment]
DataTable nicht benutzen, wenn mensch in der Cloud arbeitet?

**Comment by Bia-Ka** [comment]
Was wäre für diese Zielsetzung denn hier eine gute Alternative?

**Comment by NMarkgraf** [comment]
> Was wäre für diese Zielsetzung denn hier eine gute Alternative?

Das kommt auf deine spezielle Zielsetzung an. -- Du hast in der Cloud Variante eben nicht so viel Speicher wie auf deinem lokalen Rechner. (Oder wie @luebby immer so schön sagt: "Einen Tod müssen wir sterben...". Nun, in diesem Fall ist es genau der. ;-) )

Wenn ich das richtig sehe ist GV2002.cvs nun 266kByte groß. Da wird der Speicher den wir für R in den Cloud-Systemen haben halt knapp. Wenn Du auch das ganze geklicke verzichten kannst, dann mag es gehen.

**Comment by Bia-Ka** [comment]
Wir brauchen an der Stelle eine gute Übersicht über die Daten. Und wir fragen danach, wie gut die individuelle Schätzung war, dafür müssen die Studis ihre Gemeinde in den Daten finden. Da wird es dann ggf. schwierig mit einer Alternative, die das leistet, oder?
Letztendlich kann man die Fehlermeldung natürlich auch einfach ignorieren, das Ergebnis wird ja angezeigt. Dann ist das Ignorieren der Fehlermeldung hier der Tod, der zu sterben ist.
